#!/usr/bin/env python
key = "bbe6ef885cea3872b7e459671081893d"

import argparse
import requests
parser = argparse.ArgumentParser()
parser.add_argument("username", help="your pastebin username")
parser.add_argument("password", help="your pastebin password")
parser.add_argument("apikey", help="your pastebin developer api key")
args = parser.parse_args()

url='http://pastebin.com/api/api_login.php'
postdata = {
	"api_dev_key" : args.apikey,
	"api_user_name" : args.username,
	"api_user_password" : args.password,
}
print(requests.post(url, data=postdata).text)

